<?php
@include('../components/head.php');
?>  
<?php
@include('../components/body.php');
@include("../components/shared/navbar.php");
@include("../components/carrers/firstsection.php");
@include("../components/carrers/joinourteam.php");
@include("../components/aboutus/circlesassociation.php");
@include("../components/aboutus/meetourteam.php");
@include("../components/aboutus/faqs.php");
@include("../components/shared/footer.php");
@include("../components/closeblody.php");
?>