<?php
@include('../components/head.php');
?>  
<?php
@include('../components/body.php');
@include("../components/shared/navbar.php");
@include('../components/home/hero.php');
@include('../components/home/partners.php');
@include('../components/home/services.php');
@include('../components/home/circlesexperts.php');
@include("../components/home/ourwellness.php");
@include("../components/home/subscribtions.php");
@include("../components/home/questions.php");
@include("../components/home/circeljourney.php");
@include("../components/home/expertsinclinic.php");
@include("../components/home/transformations.php");
@include("../components/home/testimonials.php");
@include("../components/home/map.php");
@include("../components/shared/footer.php");
@include("../components/closeblody.php");
?>